name: Deploy Application

on:
  push:
    branches:
      - main

env:
  EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}  # EC2 instance ID'si
  AWS_REGION: eu-central-1

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to EC2 using AWS SSM
        run: |
          # Dosyaları S3'e yükle
          aws s3 cp backend/ s3://${{ secrets.DEPLOYMENT_BUCKET }}/backend/ --recursive

          # SSM Run Command ile deployment
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters commands=[
              "cd ~/video-platform",
              "aws s3 sync s3://${{ secrets.DEPLOYMENT_BUCKET }}/backend/ .",
              "docker-compose down",
              "docker-compose up -d"
            ]

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
          if [ -f "package.json" ]; then
            npm install
          else
            echo "package.json not found in frontend directory"
            exit 1
          fi
        
      - name: Run Frontend Tests
        working-directory: ./frontend
        run: |
          if [ -f "package.json" ]; then
            npm test || true
          fi
        
      - name: Build Frontend
        working-directory: ./frontend
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        run: npm run build
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          
      - name: Deploy to S3
        run: |
          if [ -d "frontend/build" ]; then
            aws s3 sync frontend/build/ s3://${{ secrets.S3_BUCKET }} --delete
          else
            echo "Build directory not found"
            exit 1
          fi
          
     